export const USER_IS_LOGGED_IN = 'USER_IS_LOGGED_IN';
export const USER_IS_SET_LOGGED_IN = 'USER_IS_SET_LOGGED_IN';

export const SHOWS_ADD_SHOWS = 'SHOWS_ADD_SHOWS';
export const SHOWS_SET_IS_LOAD = 'SHOWS_SET_IS_LOAD';
export const SHOWS_SET_PAGE = 'SHOWS_SET_PAGE';
export const SHOWS_IS_FROM_SEARCH = 'SHOWS_IS_FROM_SEARCH';

export const SHOW_SET_SHOW = 'SHOW_SET_SHOW';
export const SHOW_SET_IS_LOAD = 'HOW_SET_IS_LOAD';

export const ACTORS_ADD_ACTORS = 'ACTORS_ADD_ACTORS';
export const ACTORS_SET_IS_LOAD = 'ACTORS_SET_IS_LOAD';

export const ACTOR_SET_ACTOR = 'ACTOR_SET_ACTOR';
export const ACTOR_SET_IS_LOAD = 'ACTOR_SET_IS_LOAD';

export const FILTER_SET_GENRE = 'FILTER_SET_GENRE';
export const FILTER_SET_ACTOR = 'FILTER_SET_ACTOR';
export const FILTER_SET_RATING_SORT = 'FILTER_SET_RATING_SORT';
