export const USER_SET_AUTH_ERROR = 'USER_SET_AUTH_ERROR';
export const USER_SET_USER = 'USER_SET_USER';
export const USER_SIGNIN_USER = 'USER_SIGNIN_USER';
export const USER_SIGNUP_USER = 'USER_SIGNUP_USER';
export const USER_SIGNOUT_USER = 'USER_SIGNOUT_USER';
// export const USER_UNSET_USER = 'USER_UNSET_USER';

export const SHOWS_SET_SHOWS = 'SHOWS_SET_SHOWS';
export const SHOWS_GET_SHOWS = 'SHOWS_GET_SHOWS';
export const SHOWS_SET_IS_LOAD = 'SHOWS_SET_IS_LOAD';
export const SHOWS_SET_PAGE = 'SHOWS_SET_PAGE';
export const SHOWS_SOULD_LOAD = 'SHOWS_SOULD_LOAD';

export const CURRENT_SHOWS_SET_SHOWS = 'CURRENT_SHOWS_SET_SHOWS';
export const CURRENT_SHOWS_GET_SHOWS = 'CURRENT_SHOWS_GET_SHOWS';
export const CURRENT_SHOWS_SET_IS_LOAD = 'CURRENT_SHOWS_SET_IS_LOAD';

export const SEARCH_SHOWS_SET_SHOWS = 'SEARCH_SHOWS_SET_SHOWS';
export const SEARCH_SHOWS_GET_SHOWS = 'SEARCH_SHOWS_GET_SHOWS';
export const SEARCH_SHOWS_SET_IS_LOAD = 'SEARCH_SHOWS_SET_IS_LOAD';

export const SHOW_SET_SHOW = 'SHOW_SET_SHOW';
export const SHOW_SET_IS_LOAD = 'HOW_SET_IS_LOAD';

export const ACTORS_SET_ACTORS = 'ACTORS_SET_ACTORS';
export const ACTORS_GET_ACTORS = 'ACTORS_GET_ACTORS';
export const ACTORS_SET_IS_LOAD = 'ACTORS_SET_IS_LOAD';

export const ACTOR_SET_ACTOR = 'ACTOR_SET_ACTOR';
export const ACTOR_GET_ACTOR = 'ACTOR_GET_ACTOR';
export const ACTOR_SET_CAST = 'ACTOR_SET_CAST';
export const ACTOR_GET_CAST = 'ACTOR_GET_CAST';
export const ACTOR_SET_IS_LOAD = 'ACTOR_SET_IS_LOAD';
export const ACTOR_SET_CAST_IS_LOAD = 'ACTOR_SET_CAST_IS_LOAD';

export const FILTER_SET_GENRE = 'FILTER_SET_GENRE';
export const FILTER_SET_RATING_SORT = 'FILTER_SET_RATING_SORT';
export const FILTER_SET_PREMIER_DATE = 'FILTER_SET_PREMIER_DATE';
export const FILTER_SET_QUERY = 'FILTER_SET_QUERY';
export const FILTER_SET_ACTOR_QUERY = 'FILTER_SET_ACTOR_QUERY';
